# Generated by Django 2.2.16 on 2022-12-22 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20221216_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_p',
            field=models.ForeignKey(blank=True, help_text='Комментарий, к которому будет относиться комментарий', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='posts.Comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
    ]
