# Generated by Django 2.2.16 on 2022-12-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20221222_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hidden_text',
            field=models.TextField(blank=True, default=None, help_text='Цитата', null=True, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_p',
            field=models.ForeignKey(blank=True, default=None, help_text='Комментарий, к которому будет относиться комментарий', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='posts.Comment', verbose_name='Комментарий'),
        ),
    ]
